### ISSUE TITLE
URL String Encoding PadId

### ISSUE THREAD

**Issue by Drake81** [EtherApp/EtherApp#1]

**Comment by fmalcher** [comment]
Could solve it: http://stackoverflow.com/questions/10786042/java-url-encoding

**Comment by fmalcher** [comment]
I've obviously encountered serious problems resolving this issue.
I tried to urlencode padIDs before feeding them to the API. _Seems_ to work fine for German umlauts, but the _$_ sign (separator between group and pad) is also being converted. The API is not capable of recognising this.
My impression is, we need a urlencode function without the $ sign?

**Comment by fmalcher** [comment]
Probably resolved with loader implementation?

**Comment by Drake81** [comment]
The Problem isn't resolved. Just hidden behind an Exception...
